Fixed the way of referencing another makefile
michaelklishin/tls-gen pull request #28
Opened 2020-12-29 17:37 UTC by anderson-fachini

Hi, the way you referenced the main Makefile in the folder basic was causing the following error message for me:
Makefile:1: *** missing separator.  Stop.

Following the [GNU make documentation](https://www.gnu.org/software/make/manual/html_node/Include.html) it indicates to use the word include instead.

2020-12-29 18:10 UTC, lukebakken requested changes
The `basic/Makefile` file is a symbolic link. Are you using Windows?

2020-12-29 23:47 UTC, anderson-fachini commented
"Both": the files are on windows, but I a accessed them using Ubuntu on Windows Subsystem Linux.

2021-01-05 15:23 UTC, lukebakken commented
OK, WSL must not deal with symbolic links correctly. I'll take your patch as a starting point to fix this. Thank you.

2021-01-05 15:30 UTC, lukebakken commented
@anderson-fachini please test the changes in #30. Thanks!

2021-01-05 15:30 UTC, closed without merging